### PR TITLE
Fix compile errors and add setting to ignore Jetsam events

### PR DESCRIPTION
**Pull request by NSExceptional**

### CODE REVIEW

**Comment by NSExceptional** [comment]
@Muirey03 I can break this into multiple separate PRs for each change if that will get it merged faster

**Comment by Muirey03** [comment]
@NSExceptional I'm so sorry I ignored this PR. I haven't been maintaining my tweaks recently but I will get this merged for you.

**Comment by NSExceptional** [comment]
Hey no worries! It happens.

Heads up, I'm gonna make some more boilerplate-y PRs cause I wanna contribute features and fixes, but this and some other stuff I haven't put up a PR for yet is blocking 😅

**Comment by NSExceptional** [comment]
Random GitHub tip: if you choose "rebase and merge" or "Squash and merge" it'll keep the commit history pretty and linear, if that's something you care about 😄  (if you're not using a git GUI client, you probably won't ever see this)

PR with merge commit:
Screenshot 2022-09-17 at 3 01 34 PM

Many PRs with 0 merge commits, using "rebase and merge":
Screenshot 2022-09-17 at 3 03 29 PM

**Comment by Muirey03** [comment]
@NSExceptional Thank you. I would be very happy if you wanted to keep maintaining Cr4shed for me now. If it wouldn't be too much bother, would you mind sending me a deb file when you would like your changes to be pushed to the repo? I don't really want to debug TravisCI build fails if I'm totally honest.

**Comment by NSExceptional** [comment]
Happy to! And sure thing, will do. You can add me as a collaborator

**Comment by NSExceptional** [comment]
@Muirey03 I see you invited me on Havoc (dunno what this is), does it give me commit access to this repo?

**Comment by Muirey03** [comment]
@NSExceptional you were already a collaborator on this repo. Havoc is where the tweak is hosted (it replaced Packix) so you can push updates to users if you'd like.

**Comment by NSExceptional** [comment]
Oh, I didn't know that! If I requested it before then I forgot. Thanks!

Happy to send you debs instead of pushing updates myself, what would you rather me do? I'm fine with either

**Comment by Muirey03** [comment]
Completely up to you. I will try my hardest to be punctual if you send me anything but you are more than welcome to do anything yourself. Please add your name to the Maintainer field in the control file if you would like :)

**Pull request merged**
